[package]
name = "Iota"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "*"
json = "*"
axum = "*"
futures-util = "*"
rustls = { version = "*", default-features = false, features = ["ring"] }
tokio-tungstenite = { version = "0.23.1", default-features = false, features = [
    "connect",
    "rustls-tls-webpki-roots",
    "tokio-rustls"
] }
cmake = "*"
tokio = { version = "*", features = ["full"] }
uuid = { version = "*", features = ["v4"] }
walkdir = "2.5.0"
sysinfo = "0.30"
serde = { version = "1.0.219", features = ["derive"] }
ratatui = { version = "*", features = ["all-widgets"]}
bytes = "*"
crossterm = "*"
color-eyre = "*"
sys-info = "*"
rand = "0.8"
rand_core = { version = "0.6", features = ["getrandom", "std"] }
base64 = "0.22.1"
once_cell = "1.21.3"
reqwest = "0.12.23"
x448 = { version = "*" }
hex = "*"
x509 = "*"
sha2 = "*"
der = "*"
pkcs8 = { version = "*", features = ["alloc"] }
tungstenite = "*"
futures = "*"
aes-gcm = "*"
hkdf = "*"
hmac = "*"
reactive-rs = "*"
