[package]
name = "Iota"
version = "0.1.0"
edition = "2024"

[dependencies]
json = "*"
axum = "*"
futures-util = "*"
rustls = { version = "*", default-features = false, features = ["ring"] }
tokio-tungstenite = { version = "0.23.1", default-features = false, features = [
    "connect",
    "rustls-tls-webpki-roots",
    "tokio-rustls"
] }
cmake = "*"
tokio = { version = "*", features = ["full"] }
uuid = { version = "*", features = ["v4"] }
walkdir = "2.5.0"
sysinfo = "*"
serde = { version = "1.0.219", features = ["derive"] }
