name: Build & Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: docker.tensamin.net
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build & Push
        run: |
          docker build -t docker.tensamin.net/iota:latest .
          docker push docker.tensamin.net/iota:latest
